version: "3.8"

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    command: ["--config=/etc/otel/otel-config.yaml"]
    configs:
      - source: otel-config
        target: /etc/otel/otel-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    networks:
      - observability
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo/tempo.yaml"]
    configs:
      - source: tempo-config
        target: /etc/tempo/tempo.yaml
    volumes:
      - tempo-data:/tmp/tempo
    networks:
      - observability
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure

  loki:
    image: grafana/loki:latest
    command: ["-config.file=/etc/loki/loki-config.yaml"]
    configs:
      - source: loki-config
        target: /etc/loki/loki-config.yaml
    volumes:
      - loki-data:/loki
    ports:
      - "3100:3100"
    networks:
      - observability
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - observability
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure

configs:
  otel-config:
    file: ./otel-config.yaml
  tempo-config:
    file: ./tempo-config.yaml
  loki-config:
    file: ./loki-config.yaml

networks:
  observability:
    driver: overlay
    attachable: true

volumes:
  tempo-data:
  loki-data:
  grafana-data:
